VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "class_Member"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public Name             As String
Public Bindable         As Variant
Public Browsable        As Variant
Public Category         As Variant
Public DefaultBind      As Variant
Public Description      As Variant
Public DisplayBind      As Variant
Public HelpContextID    As Variant
Public Hidden           As Variant
Public PropertyPage     As Variant
Public RequestEdit      As Variant
Public StandardMethod   As Variant
Public UIDefault        As Variant
